version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    volumes:
      - chroma_data:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mcp-ts-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  chroma_data:
