services:
  mcp-aws-ts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-aws-ts
    restart: unless-stopped
    # For MCP stdio communication, we'll use stdin_open and tty
    stdin_open: true
    tty: true
    # Environment variables
    environment:
      - NODE_ENV=production
    # If you need to expose ports in the future
    # ports:
    #   - "3000:3000"
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    restart: unless-stopped
    volumes:
      - chroma_data:/data
    # No ports exposed, only internal communication
    
volumes:
  chroma_data: